"""Tests for the submitters package: handle cache, factory, transport helpers."""

from __future__ import annotations

import pytest

from dockyard_k8s.submitters import (
    SubmissionHandle,
    build_submitter,
    handle_path,
    load_handle,
    save_handle,
)
from dockyard_k8s.submitters.exec_ import (
    ExecSubmitter,
    _render_launcher,
    _validate_run_id,
)
from dockyard_k8s.submitters.portforward import (
    PortForwardSubmitter,
    _prepend_env_exports,
)


@pytest.fixture(autouse=True)
def _isolate_cache(tmp_path, monkeypatch):
    monkeypatch.setenv("DOCKYARD_K8S_CACHE_DIR", str(tmp_path / "cache"))


class TestHandleCache:
    def test_roundtrip(self) -> None:
        h = SubmissionHandle(
            kind="exec", run_id="r1", cluster_name="c", namespace="ns",
            pod="c-head", tmp_dir="/tmp/dockyard-r1",
        )
        save_handle(h)
        loaded = load_handle("r1")
        assert loaded == h

    def test_load_missing_returns_none(self) -> None:
        assert load_handle("nope") is None

    def test_cache_dir_env_honoured(self, tmp_path) -> None:
        assert str(tmp_path / "cache") in str(handle_path("x"))

    def test_corrupt_handle_returns_none(self) -> None:
        p = handle_path("bad")
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text("{not json")
        assert load_handle("bad") is None


class TestBuildSubmitter:
    def test_exec_selected(self, make_infra) -> None:
        infra = make_infra(submit={"submitter": "exec", "execTmpDir": "/workspace/tmp"})
        sub = build_submitter(infra)
        assert isinstance(sub, ExecSubmitter)

    def test_portforward_default(self, make_infra) -> None:
        assert isinstance(build_submitter(make_infra()), PortForwardSubmitter)


class TestPortForwardHelpers:
    def test_prepend_env_exports(self) -> None:
        out = _prepend_env_exports("python run.py", {"A": "1", "B": "x y"})
        lines = out.splitlines()
        assert lines[0] == "export A=1"
        assert lines[1] == "export B='x y'"  # shell-quoted
        assert lines[-1] == "python run.py"

    def test_prepend_noop_when_empty(self) -> None:
        assert _prepend_env_exports("python run.py", {}) == "python run.py"

    def test_invalid_env_key_rejected(self) -> None:
        with pytest.raises(ValueError, match="invalid env var name"):
            _prepend_env_exports("x", {"1BAD": "v"})


class TestExecHelpers:
    def test_validate_run_id_ok(self) -> None:
        _validate_run_id("training-123_a.b")  # no raise

    @pytest.mark.parametrize("bad", ["", "has space", "bad/slash"])
    def test_validate_run_id_rejects(self, bad: str) -> None:
        with pytest.raises(ValueError):
            _validate_run_id(bad)

    def test_render_launcher_exports_and_exitcode(self) -> None:
        script = _render_launcher(
            run_id="r1",
            env_vars={"FOO": "bar"},
            user_entrypoint="python run.py",
            exitcode_path="/tmp/dockyard-r1/exitcode",
        )
        assert "export DOCKYARD_K8S_RUN_ID=r1" in script
        assert "export FOO=bar" in script
        assert "python run.py" in script
        assert "echo $ec > /tmp/dockyard-r1/exitcode" in script
        assert "Generated by dockyard-k8s" in script

    def test_exec_rejects_working_dir(self, tmp_path) -> None:
        sub = ExecSubmitter(exec_tmp_dir="/tmp")
        with pytest.raises(ValueError, match="does not support working_dir"):
            sub.submit(
                "c", "ns", entrypoint="x", run_id="r1", working_dir=tmp_path
            )
