"""Sphinx configuration for the dockyard_rl documentation.

The API reference is generated by sphinx-autodoc2, which reads the source
statically (no import), so the docs build in an environment without the
runtime dependencies (torch, vLLM, jax) installed.
"""

from __future__ import annotations

from datetime import datetime

# Project metadata
project = "dockyard_rl"
author = "Kartik A (NullVoider)"
copyright = f"{datetime.now():%Y}, Kartik A (NullVoider)"
release = "0.1.0.dev0"
version = "0.1"

# Extensions
extensions = [
    "myst_parser",
    "autodoc2",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    "sphinx.ext.doctest",
    "sphinx_copybutton",
    "sphinxcontrib.mermaid",
]

# MyST (Markdown) features
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "fieldlist",
    "tasklist",
    "attrs_inline",
]
myst_heading_anchors = 3
# Render ```mermaid fenced blocks via the sphinxcontrib-mermaid directive
# (client-side mermaid.js in HTML output) instead of as highlighted code.
myst_fence_as_directive = ["mermaid"]

# autodoc2 — static API extraction from the package source.
# docs/ lives inside the package directory, so "../" resolves to the
# dockyard_rl package root.
autodoc2_packages = [
    {"path": "..", "module": "dockyard_rl"},
]
autodoc2_render_plugin = "myst"
autodoc2_output_dir = "apidocs"
autodoc2_hidden_objects = ["dunder", "private", "inherited"]

# Source / build
source_suffix = {
    ".md": "markdown",
    ".rst": "restructuredtext",
}
templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "README.md"]

# HTML output
html_theme = "furo"
html_title = "dockyard_rl"
html_static_path = ["_static"]
html_theme_options = {
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
}

# Cross-project references
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "ray": ("https://docs.ray.io/en/latest", None),
}
intersphinx_disabled_reftypes = ["*"]
